check_sane_mount: if mknod does not work, test if bind-mounting /dev/null works

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1781,10 +1781,24 @@ check_sane_mount () {
 		  lxc|lxc-libvirt|mmdebstrap-unshare)
 		    ;;
 		  *)
-		    mknod "$1/test-dev-null" c 1 3 || return 1
-		    if ! echo test > "$1/test-dev-null"; then
-			rm -f "$1/test-dev-null"
-				return 1
+		    if mknod "$1/test-dev-null" c 1 3 2>/dev/null; then
+			if ! echo test > "$1/test-dev-null"; then
+			    rm -f "$1/test-dev-null"
+			    return 1
+			fi
+		    else
+			# mknod failed. Try if bind-mounting works
+			touch "$1/test-dev-null"
+			if ! mount -o bind /dev/null "$1/test-dev-null"; then
+			    rm -f "$1/test-dev-null"
+			    return 1
+			fi
+			if ! echo test > "$1/test-dev-null"; then
+			    umount "$1/test-dev-null"
+			    rm -f "$1/test-dev-null"
+			    return 1
+			fi
+			umount "$1/test-dev-null"
 		    fi
 		    rm -f "$1/test-dev-null"
 		    ;;
